### ISSUE TITLE
Bug in hs.menubar:popupMenu()

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1367]
On my MacBook Pro if I have an external screen attached, the right-click menu only works on the external display, not on my laptop screen.

**Comment by latenitefilms** [comment]
@randomeizer - I'm gonna assign this to you for now as I'll be out of action for a few days - but will assign back to me if I get a chance to do it before you.

**Comment by latenitefilms** [comment]
Problem code: https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/finalcutpro/viewer/overlays.lua#L619

**Comment by randomeizer** [comment]
So, I believe the problem code is actually in the modifications you made for "dark mode" in hs.menubar. When I revert to Chris's last version, the menubar appears as expected (albeit in "light mode"). Looking at the code, my guess is that the problem is that the new NSWindow you're creating is being created on the primary NSScreen, not the secondary NSScreen. As such, when the menubar gets created, it's off-screen on the primary screen, and is not visible when triggered.

I pushed an attempted fix into the `feature/issue-1367` branch in CP-App. It doesn't work because each NSScreen's `frame` has an origin of 0,0, rather than being relative to the main screen, and I haven't found a way to convert it yet. I'm sure it's out there, just haven't come across it.

**Comment by latenitefilms** [comment]
@randomeizer - You had a late night! :)

Ahha! That makes perfect sense! I didn't even think it could be a bug in the `hs.menubar` - thanks for testing! I'll investigate!

**Comment by latenitefilms** [comment]
Maybe related: https://stackoverflow.com/a/21826195

**Comment by randomeizer** [comment]
Yeah, it's related, but not exactly sure how to use it. I'm not 100% certain what coordinate system the initial point we receive for the mouse location is in. I think it's in the Screen system, but for the primary screen, not the screen the clock occurred on. Thus, I'm not sure how to convert it exactly.

**Comment by latenitefilms** [comment]
I've tried a bunch of things, but still not having much luck. Will keep trying tomorrow.

**Comment by latenitefilms** [comment]
Fixed here: https://github.com/CommandPost/CommandPost-App/commit/1eeb75aeac181ea9de00716937ed78a0decbc4e7
